"""
Pydantic V2 Schemas for Real-Time Intra-Session Event Payload Validation.
Includes input sanity bounds to prevent out-of-distribution inference distortion.
"""
from typing import Optional
from pydantic import BaseModel, Field


class LiveEventInput(BaseModel):
    """Real-time event payload captured from storefront dataLayer or Server-Side proxy."""
    visitor_type_encoded: int = Field(..., ge=0, le=2, description="0: New_Visitor, 1: Returning_Visitor, 2: Other")
    traffic_type: int = Field(..., ge=1, le=20, description="Traffic source category ID (1-20)")
    session_duration_sec: float = Field(..., ge=0.0, le=86400.0, description="Session duration in seconds (Max 24h)")
    product_views_count: int = Field(..., ge=0, le=500, description="Count of product pages viewed (Max 500)")
    cart_add_count: int = Field(..., ge=0, le=100, description="Count of items added to cart (Max 100)")
    price_sum_viewed: float = Field(..., ge=0.0, le=10000.0, description="Cumulative sum of item prices viewed ($) (Max $10,000)")
    time_since_last_action: float = Field(..., ge=0.0, le=7200.0, description="Inactivity delay in seconds (Max 2h)")
    
    # Optional Overrides & Context
    cart_value_override: Optional[float] = Field(None, ge=0.0, le=10000.0, description="Current shopping cart value ($) if available")
    session_id: Optional[str] = Field(None, max_length=128, description="GA4 client_id or session UUID")
    tracking_mode: Optional[str] = Field("client_side", description="'client_side' or 'server_side'")


class PredictionResponse(BaseModel):
    """Synchronous JSON response returned to Google Tag Manager / Storefront."""
    trigger_discount: bool = Field(..., description="Whether Expected Monetary Value is positive")
    net_emv_dollars: Optional[float] = Field(None, description="Net expected profit gain ($) [Verbose Mode]")
    cate_uplift: Optional[float] = Field(None, description="Conditional Average Treatment Effect uplift [Verbose Mode]")
    p_control: Optional[float] = Field(None, description="Conversion probability without discount [Verbose Mode]")
    p_treatment: Optional[float] = Field(None, description="Conversion probability with discount [Verbose Mode]")
    model_source: str = Field(..., description="'trained_artifact' or 'fallback_heuristic'")
    is_holdout: bool = Field(False, description="True if session was randomly assigned to exploration holdout")
    version: str = Field(..., description="API Version")
    tracking_mode: str = Field("client_side", description="'client_side' or 'server_side'")
    trust_level: str = Field(
        ...,
        description=(
            "'authoritative' (server-to-server key: safe to act on directly) or "
            "'advisory' (client-side/public key: UI-hint only, must NOT be wired "
            "to real coupon/checkout actions — confirm via an authoritative call)"
        )
    )

class ConfirmDiscountInput(BaseModel):
    """Server-side authoritative request payload for final checkout discount confirmation."""
    event: LiveEventInput
    server_cart_value: float = Field(..., ge=0.0, description="Definitive cart value from server-side order API")

class ConfirmDiscountResponse(BaseModel):
    """Final authoritative decision response for coupon minting/checkout application."""
    apply_discount: bool = Field(..., description="Final authorization to apply the discount")
    net_emv_dollars: Optional[float] = Field(None, description="Risk-adjusted EMV generated by this intervention")
    session_id: Optional[str] = Field(None, description="Corresponding session ID for tracing")
